name: StaffNotes
version: '${project.version}'
main: org.thedevjacob.staffnotes.StaffNotes
api-version: '1.20'

commands:
  note:
    description: Manage notes.
    usage: /<command>
    permission: StaffNotes.notes